### ISSUE TITLE
Size mismatch in the morphing example

### ISSUE THREAD

**Issue by kalenkovich** [HidekiKawahara/legacy_STRAIGHT#1]
I am trying to run the morphing example from the docs. When I get to morphing in the STRAIGHT and run the following line:

```matlab
mObject3 = directSTRAIGHTmorphing(neutralHai,angryHai,0.5,'linear');
```
I get the following error:

> Subscripted assignment dimension mismatch.
> 
> Error in directSTRAIGHTmorphing (line 45)
> ap(1:nr1,1:nc1) = (1-mRate)*mObject1.aperiodicityIndex;

Debugging shows that `nr1 = 2049` while `size(mObject1.aperiodicityIndex, 1) = 1025`. I am confused as to what might cause this.

**Comment by HidekiKawahara** [comment]
Thank you for pointing out this.
This problem is caused by the mismatch in default parameter setting in exstraightsource.m and exstraightspec.m .
Please edit the line 230 of  exstraightsource.m by changeing 40 to 80
prm.F0defaultWindowLength = 80; % default frame length for pitch extraction (ms)

This fixes the problem.
I will check the other side effects. If it is OK, then, I will update the code.

**Comment by HidekiKawahara** [comment]
I checked side effects and found it is OK.
