### ISSUE TITLE
Sound quality is bad by running the "quick start" example code

### ISSUE THREAD

**Issue by fxw915** [HidekiKawahara/legacy_STRAIGHT#2]
Hi all, 
I ran the command line code in the quick start example on MATLAB R2018b. And the synthesized sound quality is really poor, filled with loud noise. Since I didn't modify the source code and the wav file, I am wondering if it is the issue with the MATLAB version or some bugs need to be fixed in source code.

**Comment by HidekiKawahara** [comment]
Thank you for your feedback. That is because the magnitude of the synthesized signal has a huge amplitude. 
max(abs(syntheszed_signal))
ans =

   2.1297e+04

Please try to save the signal as follows.
audiowrite('testSyn.wav', syntheszed_signal / max(abs(syntheszed_signal)) * 0.8, fs);
I tested on Mac and Windows and found the synthesized signal sounds reasonable.
Please find the generated file.
Thank you again.

[testSyn.wav.zip](https://github.com/HidekiKawahara/legacy_STRAIGHT/files/2766912/testSyn.wav.zip)

**Comment by fxw915** [comment]
@HidekiKawahara Thanks a lot! That solves the problem!
